package at.ac.fhcampuswien.fhmdb;

public enum Genres {
    ACTION, ADVENTURE, ANIMATION, BIOGRAPHY, COMEDY,
    CRIME, DRAMA, DOCUMENTARY, FAMILY, FANTASY,
    HISTORY, HORROR, MUSICAL, MYSTERY, ROMANCE,
    SCIENCE_FICTION, SPORT, THRILLER, WAR, ALL, WESTERN
}
